# ────────────────────────────────────────────────
# Jekyll Site Configuration — Chirpy Theme
# ────────────────────────────────────────────────

# Theme & Locale
theme: jekyll-theme-chirpy
lang: en
timezone: Africa/Johannesburg

# ────────────────────────────────────────────────
# Site Identity
# ────────────────────────────────────────────────
title: "tibane"
tagline: "Exploring low-level development and the craft of pwning."
description: >-
  Portfolio and blog of an aspiring offensive security researcher.
  Red team mindset. Real-world attack surface. Writeups, tools, and notes from the field.

url: "https://tibane0.github.io"
baseurl: ""         # leave empty for GitHub Pages root

avatar: "assets/images/me.jpeg"              # Sidebar avatar
social_preview_image: "assets/images/me.jpeg" # og:image for SEO

# ────────────────────────────────────────────────
# Author & Social Links
# ────────────────────────────────────────────────
social:
  name: "Nkateko Tibane"
  email: "nkatekotibane101@gmail.com"
  links:
    - "https://twitter.com/tibane101"
    - "https://github.com/tibane0"
    - "https://www.linkedin.com/in/nkatekotibane"
    

github:
  username: tibane0
twitter:
  username: tibane101
linkedin:
  username: nkatekotibane

# ────────────────────────────────────────────────
# SEO / Verification
# ────────────────────────────────────────────────
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# ────────────────────────────────────────────────
# Analytics (enable only one provider if needed)
# ────────────────────────────────────────────────
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:    # supports 'goatcounter'

# ────────────────────────────────────────────────
# Appearance
# ────────────────────────────────────────────────
theme_mode:        # [light | dark] empty = system default
cdn:               # e.g. 'https://cdn.example.com'
toc: true          # show TOC in posts globally
paginate: 10

# ────────────────────────────────────────────────
# Comments
# ────────────────────────────────────────────────
comments:
  provider: giscus
  giscus:
    repo: "tibane0/tibane0.github.io"
    repo_id: "R_kgDOOv_aMg"
    category: "General"
    category_id: "DIC_kwDOOv_aMs4CqjgI"
    mapping: pathname
    strict: 0
    input_position: bottom
    lang:
    reactions_enabled: 1

# ────────────────────────────────────────────────
# Progressive Web App
# ────────────────────────────────────────────────
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"

# ────────────────────────────────────────────────
# Markdown & Syntax Highlighting
# ────────────────────────────────────────────────
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1
    span:
      line_numbers: false

# ────────────────────────────────────────────────
# Collections & Defaults
# ────────────────────────────────────────────────
collections:
  tabs:
    output: true
    sort_by: order
  notes:
    output: true
    permalink: /notes/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /post/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: ""
      type: notes
    values:
      layout: page
      toc: true
      permalink: /notes/:path/

# ────────────────────────────────────────────────
# Build & Optimization
# ────────────────────────────────────────────────
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - ".github"
  - ".obsidian"
  - "..vscode"
  - "*.config.js"
  - "package*.json"

# ────────────────────────────────────────────────
# Jekyll Archives
# ────────────────────────────────────────────────
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
